import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Moja appka via Create Next App",
  description: "Generated by create next app. Demo projekt v Next.js",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
      <header>
        <nav>
          <Link href="/">Home</Link> | <Link href="/about">About</Link> | <Link href="/blog">Blog</Link>
        </nav>
      </header>
        {children}
      </body>
    </html>
  );
}
{/*<footer>© 2025 Moja appka</footer>*/}